.\" Copyright (C) 2012  Southern Storm Software, Pty Ltd.
.\"
.\" This work is licensed under the Creative Commons Attribution-ShareAlike
.\" 2.5 Generic License. To view a copy of this license, visit
.\" http://creativecommons.org/licenses/by-sa/2.5/ or send a letter
.\" to Creative Commons, 444 Castro Street, Suite 900, Mountain View,
.\" California, 94041, USA.
.\"
.TH ardpicprog 1 "May 2012" "Southern Storm Software"
.SH NAME
ardpicprog \- Arduino-based programmer for PIC devices
.SH SYNOPSIS
\fBardpicprog\fR \fB--quiet -q --warranty --copying --help -h --device\fR \fIDEVTYPE\fI \fB-d\fR \fIDEVTYPE\fR \fB--pic-serial-port\fR \fIPORT\fR \fB-p\fR \fIPORT\fR \fB--input-hexfile\fR \fIINPUT\fR \fB-i\fR \fIINPUT\fR \fB--output-hexfile\fR \fIOUTPUT\fR \fB-o\fR \fIOUTPUT\fR \fB--ihx8m --ihx16 --ihx32 --cc-hexfile\fR \fICCFILE\fR \fB-c\fR \fICCFILE\fR \fB--skip-ones --erase --burn --force-calibration --list-devices --speed\fR \fISPEED\fR
.SH ENVIRONMENT
.B PIC_DEVICE
.B PIC_PORT
.SH DESCRIPTION
See <URL:http://rweather.github.com/ardpicprog/host_program.html>.
.SH OPTIONS
See <URL:http://rweather.github.com/ardpicprog/host_program.html>.
.SH "AUTHOR"
Written by Southern Storm Software, Pty Ltd.

http://rweather.github.com/ardpicprog/
.SH "SEE ALSO"
picprog(1)
